### PR TITLE
Update orb.yml

### PR DESCRIPTION
**Pull request by luchenyuxx**
Update goss version to have http header check

### CODE REVIEW

**Comment by dud225** [comment]
OK for the change but this needs to be tested first

**Comment by luchenyuxx** [comment]
@dud225 how to test this change?

**Comment by dud225** [comment]
You need to retrieve the test orb generated by the CI and test it at least on the most prominent projects

**Comment by luchenyuxx** [comment]
@dud225 tested on this PR https://github.com/LedgerHQ/countervalue-service/pull/68

**Comment by luchenyuxx** [comment]
@dud225 Unable to test it on vault api on my fork: https://github.com/luchenyuxx/ledger-vault-api/tree/test-orb. need permission to access orb. need permission to create branch on origin.

**Comment by luchenyuxx** [comment]
image

I have this setting in my circleci conf

image

but I still got this

**Pull request merged**
